export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FORGOT_PASSWORD_EMAIL_SEARCH = 'FORGOT_PASSWORD_EMAIL_SEARCH';
export const VERIFY_USER_FOR_PASSWORD_RESET = 'VERIFY_USER_FOR_PASSWORD_RESET';

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const GET_PLAYLIST = 'GET_PLAYLIST';
export const PLAYLISTS_LOADING = 'PLAYLISTS_LOADING';
export const PLAYLIST_NOT_FOUND = 'PLAYLIST_NOT_FOUND';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const CLEAR_PLAYLISTS = 'CLEAR_PLAYLISTS';
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';