// Type: Auth
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FORGOT_PASSWORD_EMAIL_SEARCH = 'FORGOT_PASSWORD_EMAIL_SEARCH';
export const VERIFY_USER_FOR_PASSWORD_RESET = 'VERIFY_USER_FOR_PASSWORD_RESET';

// Type: Playlist
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const GET_PLAYLIST = 'GET_PLAYLIST';
export const PLAYLISTS_LOADING = 'PLAYLISTS_LOADING';
export const PLAYLIST_NOT_FOUND = 'PLAYLIST_NOT_FOUND';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_ALL_PLAYLISTS = 'GET_ALL_PLAYLISTS';
export const CLEAR_PLAYLISTS = 'CLEAR_PLAYLISTS';
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';
export const EDIT_PLAYLIST = 'EDIT_PLAYLIST';

// Type: Account
export const SET_AVATAR_IMAGE = 'SET_AVATAR_IMAGE';

// Type: Messenger
export const CREATE_MESSAGE_ROOM = 'CREATE_MESSAGE_ROOM';
export const GET_MESSAGE_ROOM = 'GET_MESSAGE_ROOM';
export const LOADING_MESSAGE_ROOM = 'LOADING_MESSAGE_ROOM';
export const CLEAR_MESSAGE_ROOM = 'CLEAR_MESSAGE_ROOM';
export const LOADING_ALL_USERS = 'LOADING_ALL_USERS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CLEAR_ALL_USERS = 'CLEAR_ALL_USERS';