export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FORGOT_PASSWORD_EMAIL_SEARCH = 'FORGOT_PASSWORD_EMAIL_SEARCH';
export const VERIFY_USER_FOR_PASSWORD_RESET = 'VERIFY_USER_FOR_PASSWORD_RESET';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';